# Generated by Django 4.1.7 on 2023-03-12 12:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0003_alter_well_last_check'),
    ]

    operations = [
        migrations.AlterField(
            model_name='well',
            name='last_check',
            field=models.DateTimeField(null=True),
        ),
    ]
